### PR TITLE
Solve problem with systemjs and browserify on all directives

### PR DESCRIPTION
**Pull request by pablorsk**

### CODE REVIEW

**Comment by mominsamir** [comment]
Can update docs if any change affects on how to use it

**Comment by pablorsk** [comment]
what is docs for you?

readme need update about ng-model (I don't fix on this commit).

Also, If you need use this library with system js, you need do this:

```javascript
import 'smdatetimerangepicker';
import 'smdatetimerangepicker/src/picker.css';
```

**Comment by mominsamir** [comment]
can you update api view,  this are displayed at here http://mominsamir.github.io/smDateTimeRangePicker/

**Comment by pablorsk** [comment]
I don't change anything about common use (final user don't need update anything). It's just a bootstrap for another scenarios.

**Comment by mominsamir** [comment]
ok thanks for your contribution

**Pull request merged**
